version: "3"
services:
  adh-web:
    depends_on:
      - adh-server
    build:
      context: .
      dockerfile: docker/live2dWeb.Dockerfile
    image: "adh-web:v0.0.1"
    container_name: "adh-web"
    links:
      - adh-server
    ports:
      - "8000:8000"
    environment:
      SERVER_HOST: "127.0.0.1"
      SERVER_PORT: "8080"
      SERVER_VERSION: "v0"
    command: /bin/sh -c "npm run build:prod ; npm run serve"
    networks:
      - mynet
  adh-server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: "adh-server:v0.0.1"
    container_name: "adh-server"
    ports:
      - "8080:8080"
    command: python3 main.py
    networks:
      - mynet
networks: 
  mynet: 
    driver: bridge