version: '3'
services:
  # awesome digital human web
  adh_web:
    build:
      context: .
      dockerfile: docker/adhWeb.Dockerfile
    image: "adh-web:v2.0.0"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./web:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - ssrf_proxy_network
      - default
  # awesome digital human server
  adh_server:
    build:
      context: .
      dockerfile: docker/adhServer.Dockerfile
    image: "adh-server:v2.0.0"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - ssrf_proxy_network
      - default
networks:
  # create a network between sandbox, api and ssrf_proxy, and can not access outside.
  ssrf_proxy_network:
    driver: bridge
    internal: true
